################################################################################
####                      PRODUCTION DOCKERFILE (NO EDITING)                ####
####                      OPENSHIFT BUILD DEPENDS ON                        ####
################################################################################

FROM postgres:15 as postgres

# Default to 5432 if PGPORT not defined
ARG PORT=${PGPORT:+5432}

# This is our time zone
ENV TZ America/Vancouver

# Install PostGIS
RUN apt-get update
RUN apt-get install -y --no-install-recommends postgresql-15-postgis-3
RUN apt-get install -y --no-install-recommends postgresql-15-postgis-3-dbgsym
RUN apt-get install -y --no-install-recommends postgresql-15-postgis-3-scripts

# Set the time zone
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Load the PostGIS extension into the database
COPY ./.docker/load_postgis.sql docker-entrypoint-initdb.d/load_postgis.sql

EXPOSE $PORT


