################################################################################
####                      DEVELOPMENT DOCKERFILE                            ####
####                      API / DB_SETUP                                    ####
################################################################################

# Install slim node 18
FROM node:18-alpine3.18 AS base

ENV HOME=/opt/app-root/src

RUN mkdir -p $HOME

WORKDIR $HOME

# Copy the package files only
# A wildcard is used to ensure both package.json AND package-lock.json are copied where available (npm@5+)
COPY package*.json ./

# Install all node modules and copy files into volumne
FROM base AS installer

COPY prisma ./prisma/

RUN npm install

ENV PATH=${HOME}/node_modules/.bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$PATH

# Copy the rest of the files
COPY . .

VOLUME ${HOME}


################################################################################
####                      DEVELOPMENT CONTAINERS                            ####
################################################################################

# Run migrations and seeds
FROM installer AS db_setup
CMD ["npm", "run", "prisma:dev-setup"]

# Run the dev api server
FROM installer AS dev_api
CMD ["npm", "run", "dev"]

# Expose the api port
EXPOSE $PORT
