name: 'Coverage Report'

on: [push]

jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: artiomtr/jest-coverage-report-action@v2
              with:
                  threshold: 90
