name: Format

on: [push]

jobs:
  Format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
      - name: Setup Node
        run: npm install
      - name: Run Format Check
        run: npm run format:check
