name: Lint

on: [push]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
      - name: Setup Node
        run: npm install
      - name: Run ESLint
        run: npm run action:lint
